---
title: "Data Analysis Workflow Example (t-SNE,UMAP,FlowSOM,MEM,RMSD)"
author: "Copyright (c) 2016-2019 by Kirsten Diggins, Sierra Barone, and Jonathan Irish, All Rights Reserved; see EULA-MEM.text for MEM license information"
date: "March 2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: inline
---
```{r setup, include=FALSE}
# Load all libraries
# If you get an error message, you will need to try re-installing packages
library(FlowSOM)
library(flowCore)
library(Biobase)
library(gplots)
library(ggplot2)
library(hexbin)
library(MEM)
?MEM
library(tidyverse)
library(Rtsne)
library(uwot)
library(viridis)
library(ggExtra)
```

```{r MEM on t-SNE, warning=FALSE}
# read FCS files into R
setwd(paste(getwd(), "/Datafiles/MCBead", sep=""))
fcs.files <-  dir(pattern ="*.fcs")

# Run MEM on the manually gated populations (each FCS files is a pop) from paper
PBMC.MEM.values.og = MEM(fcs.files, transform = TRUE, cofactor = 5, 
                 choose.markers = FALSE, markers = "2,13,14,21,23:55", choose.ref = FALSE, zero.ref = FALSE, rename.markers = FALSE,
                 file.is.clust = FALSE, add.fileID = FALSE, IQR.thresh = NULL)

# build MEM heatmap and output enrichment scores
build.heatmaps(PBMC.MEM.values.og, cluster.MEM = "none", cluster.medians = "none", 
               display.thresh = 1, newWindow.heatmaps=FALSE, output.files = FALSE, labels = TRUE, only.MEMheatmap = FALSE)


# prepare data for use in UMAP
data.with.ID <- list()
for (a in 1:length(fcs.files)){
  FCS = read.FCS(fcs.files[a])
  data = as.data.frame(FCS@exprs)
  fileID = as.factor(rep(a,nrow(data)))
  data.with.ID[[a]] = cbind(data,fileID)
  colnames(data.with.ID[[a]])[ncol(data.with.ID[[a]])] <- 'File ID'
  }
PBMC.combined.data = do.call(rbind, data.with.ID)
chosen.markers = PBMC.combined.data[,c(2,13,14,21,23:55)]
transformed.chosen.markers <- chosen.markers %>%
  mutate_all(function(x) asinh(x/35))
overall_seed = 43
```

```{r UMAP}
# Run UMAP on all surface markers
set.seed(overall_seed)
PBMCumap <- umap(transformed.chosen.markers, ret_model = TRUE, n_threads = 1)
PBMC.umap.data = as.data.frame(PBMCumap$embedding)

range <- apply(apply(PBMC.umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1]/range[2])

# UMAP flat dot plot and density dot plot
UMAP.plot <- data.frame(x = PBMC.umap.data[,1], y = PBMC.umap.data[,2])

ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + geom_point(aes(x=x, y=y), cex = 1) + labs( x = "UMAP 1", y = "UMAP 2", title = "UMAP") + theme_bw() + labs(caption = "UMAP")

ggplot(UMAP.plot, aes(x=x, y=y)) + coord_fixed(ratio = graphical.ratio)  + geom_bin2d(bins = 128) + 
  scale_fill_viridis_c(option = "A", trans = "sqrt") + scale_x_continuous(expand = c(0.1,0)) + 
  scale_y_continuous(expand = c(0.1,0)) + labs(x = "UMAP 1", y = "UMAP 2",title = "UMAP") + theme_bw() + labs(caption = "UMAP")
```


```{r FlowSOM on UMAP}
# Run FlowSOM on the UMAP axes
umap.matrix <- as.matrix(PBMC.umap.data)

# create flowFrame
UMAP.metadata <- data.frame(name = dimnames(umap.matrix)[[2]], desc = paste('UMAP', dimnames(umap.matrix)[[2]]))
UMAP.metadata$range <- apply(apply(umap.matrix, 2, range), 2, diff)
UMAP.metadata$minRange <- apply(umap.matrix, 2, min)
UMAP.metadata$maxRange <- apply(umap.matrix, 2, max)
umap.flowframe <- new("flowFrame", exprs=umap.matrix, 
                      parameters = AnnotatedDataFrame(UMAP.metadata))

# implement the FlowSOM on the data 
PBMC.fsom <- FlowSOM(umap.flowframe, compensate = FALSE, transform = FALSE, 
                toTransform=c(1:2), scale = TRUE, colsToUse = c(1:2), nClus = 38, seed = overall_seed)
PBMC.FlowSOM.clusters <- as.matrix(PBMC.fsom[[2]][PBMC.fsom[[1]]$map$mapping[,1]])

# plot FlowSOM clusters on UMAP axes
ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + geom_point(aes(x=x, y=y, color=PBMC.FlowSOM.clusters),cex = 1.5) + labs(x = "UMAP 1", y = "UMAP 2",title = "FlowSOM Clustering on UMAP Axes", color = "FlowSOM Cluster") + theme_bw() + labs(caption = "FlowSOM")
```

```{r MEM on UMAP/FlowSOM Clusters}
# Run MEM on the FlowSOM clusters from UMAP
cluster = as.numeric(as.vector((PBMC.FlowSOM.clusters)))
PBMC.MEM.data = cbind(transformed.chosen.markers,cluster)

PBMC.MEM.values.uf = MEM(PBMC.MEM.data, transform = FALSE, cofactor = 15, 
                 choose.markers = FALSE, markers = "all", choose.ref = FALSE, zero.ref = FALSE, rename.markers = FALSE,
                 file.is.clust = FALSE, add.fileID = FALSE, IQR.thresh = NULL)

# build MEM heatmap and output enrichment scores
build.heatmaps(PBMC.MEM.values.uf, cluster.MEM = "none", cluster.medians = "none", 
               display.thresh = 1, newWindow.heatmaps=FALSE, output.files = FALSE, labels = TRUE, only.MEMheatmap = FALSE)
```


```{r RMSD for All Clusters}
# RMSD to compare labels from all populations
og.MEM.scores = as.data.frame(PBMC.MEM.values.og[[5]])
rownames(og.MEM.scores) = paste0(rownames(og.MEM.scores)," Manual")
uf.MEM.scores = as.data.frame(PBMC.MEM.values.uf[[5]])
rownames(uf.MEM.scores) = paste0(rownames(uf.MEM.scores),' UMAP')
all.MEM.values = as.matrix(rbind(uf.MEM.scores,og.MEM.scores))

RMSD_vals <- MEM_RMSD(all.MEM.values,format=NULL,newWindow.heatmaps=FALSE,output.matrix = FALSE)

```
